name: apartment_staff_mobile
description: Ứng dụng Flutter cho nhân viên xử lý yêu cầu cư dân
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

