name: apartment_resident_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.2.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  webview_flutter: ^4.8.0
  app_links: ^6.3.2
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
