# Script to update database schema
Write-Host "=== CẬP NHẬT DATABASE SCHEMA ==="
Write-Host ""
Write-Host "Vui lòng chạy SQL sau trong MySQL client của bạn:"
Write-Host ""
Write-Host "USE ApartmentDB;"
Write-Host "ALTER TABLE facilities MODIFY COLUMN opening_schedule LONGTEXT NULL COMMENT 'Lịch mở cửa theo tuần';"
Write-Host ""
Write-Host "Sau khi chạy xong, hãy restart backend và test lại."
Write-Host ""
Write-Host "Hoặc bạn có thể:"
Write-Host "1. Mở MySQL Workbench hoặc phpMyAdmin"
Write-Host "2. Chọn database ApartmentDB"
Write-Host "3. Chạy lệnh ALTER TABLE facilities MODIFY COLUMN opening_schedule LONGTEXT NULL;"
Write-Host ""
Write-Host "=== END ==="
